version: "3.0"

services:
  backend:
    image: "supersolik/nosql2020-battles-backend:latest"
    environment:
      - MONGODB_URI=mongodb://localhost:27018
    network_mode: host

  frontend:
    image: "supersolik/nosql2020-battles-frontend:latest"
    network_mode: host

  db:
    image: mongo
    command: mongod --port 27018
    restart: always
    network_mode: host
