version: "3.0"

services:
  backend:
    image: "supersolik/nosql2020-battles-backend:latest"
    environment:
      - MONGODB_HOST=db
    ports:
      - 3030:3030
    network_mode: host

  frontend:
    image: "supersolik/nosql2020-battles-frontend:latest"
    ports:
      - 4200:4200
    network_mode: host

  db:
    image: mongo
    restart: always
